-- begin DEMOCUSTOMFILTER_BOOK
alter table DEMOCUSTOMFILTER_BOOK add constraint FK_DEMOCUSTOMFILTER_BOOK_AUTHOR foreign key (AUTHOR_ID) references DEMOCUSTOMFILTER_AUTHOR(ID)^
create index IDX_DEMOCUSTOMFILTER_BOOK_AUTHOR on DEMOCUSTOMFILTER_BOOK (AUTHOR_ID)^
-- end DEMOCUSTOMFILTER_BOOK
